version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: cpr_sdk
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: cpr_sdk
    target-branch: main
