repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
        exclude: tests/data/.*\.json
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.246'
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pyright
        name: pyright (backend)
        entry: pyright
        language: node
        types: [python]
        additional_dependencies: ['pyright@1.1.294']

# TODO more checks? e.g. bandit, safety, snyk, ...
