services:
  vespatest:
    image: vespaengine/vespa:latest
    container_name: vespatest
    ports:
      - 8080:8080
      - 19071:19071
    healthcheck:
      test: curl -s -f http://vespatest:19071/status.html >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  backend:
    environment:
      PYTHONDONTWRITEBYTECODE: 0
      VESPA_URL: http://vespatest:8080
    volumes:
      - ./:/cpr-backend/:ro
    depends_on:
      vespatest:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@cpr.com
      PGADMIN_DEFAULT_PASSWORD: climatepolicyradar
