include:
  - ./concepts-api/docker-compose.yml
  - ./families-api/docker-compose.yml
  - ./geographies-api/docker-compose.yml

services:
  # Override service names and ports to avoid conflicts
  concepts-api:
    extends:
      file: ./concepts-api/docker-compose.yml
      service: app
    container_name: concepts-api
    ports:
      - "8080:8080"

  families-api:
    extends:
      file: ./families-api/docker-compose.yml
      service: app
    container_name: families-api
    ports:
      - "8081:8080"
    depends_on:
      - families-db

  families-db:
    extends:
      file: ./families-api/docker-compose.yml
      service: db
    container_name: families-db
    ports:
      - "5432:5432"

  geographies-api:
    extends:
      file: ./geographies-api/docker-compose.yml
      service: app
    container_name: geographies-api
    ports:
      - "8082:8080"