# Shipyard compose: backend services with route/readiness/liveness labels.
# See https://docs.shipyard.build/docker-compose#supported-service-labels
# Ensure backend-api/.env exists (e.g. copy from backend-api/.env.example) for backend + backend_db.
#
# Inter-service URLs: use Docker Compose service name + container port. Requests use the full path
# (e.g. CONCEPTS_API_URL + "/concepts/..."). Set env vars per service that calls another; for the
# public "one link" (e.g. frontend or redirects), use Shipyard secrets to inject the env URL or
# SHIPYARD_ENVIRONMENT_URL in CI.

version: "3.8"

services:
  # ---------------------------------------------------------------------------
  # backend-api (Vespa + Postgres + FastAPI)
  # ---------------------------------------------------------------------------
  vespatest:
    image: vespaengine/vespa:8.396.18
    container_name: vespatest
    ports:
      - "8080"
      - "19071"
    healthcheck:
      test: curl -s -f http://vespatest:19071/status.html >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  backend_db:
    image: postgres:14
    restart: always
    env_file:
      - backend-api/.env
    ports:
      - "5432"
    volumes:
      - db-data-backend:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U navigator_admin]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    image: navigator-backend
    container_name: backend-api
    command: /bin/bash /app/startup.sh
    tty: true
    ports:
      - "8888"
    environment:
      PYTHONPATH: .
      VESPA_URL: http://vespatest:8080
      # Internal URLs for service-to-service (hostname = compose service name, port = container port)
      CONCEPTS_API_URL: http://concepts-api:8080
      FAMILIES_API_URL: http://families-api:8080
      GEOGRAPHIES_API_URL: http://geographies-api:8080
    env_file:
      - backend-api/.env
    depends_on:
      backend_db:
        condition: service_healthy
      vespatest:
        condition: service_healthy
    healthcheck:
      test: curl -s -f http://backend:8888/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 30
    labels:
      shipyard.route: /
      shipyard.primary-route: true
      shipyard.readiness.http.path: /health
      shipyard.readiness.initial_delay: "10"
      shipyard.liveness.http.path: /health
      shipyard.liveness.initial_delay: "10"

  # ---------------------------------------------------------------------------
  # concepts-api (FastAPI) — path prefix /concepts
  # ---------------------------------------------------------------------------
  concepts-api:
    build:
      context: .
      dockerfile: concepts-api/Dockerfile
    container_name: concepts-api
    ports:
      - "8080"
    labels:
      shipyard.route: /concepts
      shipyard.readiness.http.path: /concepts/health
      shipyard.readiness.initial_delay: "10"
      shipyard.liveness.http.path: /concepts/health
      shipyard.liveness.initial_delay: "10"

  # ---------------------------------------------------------------------------
  # families-api (Postgres + FastAPI) — path prefix /families
  # ---------------------------------------------------------------------------
  families-api-db:
    image: postgres:17
    container_name: families-api-db
    environment:
      POSTGRES_USER: navigator_admin
      POSTGRES_PASSWORD: navigator_admin
      POSTGRES_DB: navigator_admin
    ports:
      - "5432"
    volumes:
      - navigator-postgres-data:/var/lib/postgresql/data
      - families-api/initial-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [CMD-SHELL, pg_isready -U navigator_admin -d navigator_admin]
      interval: 5s
      timeout: 5s
      retries: 10

  families-api:
    build:
      context: .
      dockerfile: families-api/Dockerfile
    container_name: families-api
    ports:
      - "8080"
    environment:
      NAVIGATOR_DATABASE_URL: postgresql://navigator_admin:navigator_admin@families-api-db:5432/navigator_admin
      CDN_URL: https://cdn.climatepolicyradar.org
    depends_on:
      families-api-db:
        condition: service_healthy
    labels:
      shipyard.route: /families
      shipyard.readiness.http.path: /families/health
      shipyard.readiness.initial_delay: "10"
      shipyard.liveness.http.path: /families/health
      shipyard.liveness.initial_delay: "10"

  # ---------------------------------------------------------------------------
  # geographies-api (LocalStack S3 + FastAPI) — path prefix /geographies
  # ---------------------------------------------------------------------------
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      GEOGRAPHIES_BUCKET: test-bucket
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-1
      DEBUG: 1
    volumes:
      - ./geographies-api/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
    ports:
      - "4566"

  geographies-api:
    build:
      context: .
      dockerfile: geographies-api/Dockerfile
    container_name: geographies-api
    ports:
      - "8080"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-1
      GEOGRAPHIES_BUCKET: test-bucket
      CDN_URL: http://localstack:4566/test-bucket
    depends_on:
      localstack:
        condition: service_started
    labels:
      shipyard.route: /geographies
      shipyard.readiness.http.path: /geographies/health
      shipyard.readiness.initial_delay: "10"
      shipyard.liveness.http.path: /geographies/health
      shipyard.liveness.initial_delay: "10"

volumes:
  db-data-backend: {}
  data-in-api-postgres-data: {}
  data-in-pipeline-load-api-postgres-data: {}
  navigator-postgres-data: {}
