{
 "title": "Health overview",
 "description": "Shows key health indicators for data in pipeline",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Documents Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_documents_processed_total{environment=\"$environment\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Errors (all)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "e2e mean duration (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cpr_data_fetching_data_in_pipeline_main_pipeline_run_duration_seconds_sum{scope=\"batch\"}/cpr_data_fetching_data_in_pipeline_main_pipeline_run_duration_seconds_count{scope=\"batch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "per document mean duration (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cpr_data_fetching_data_in_pipeline_main_pipeline_run_duration_seconds_sum{scope=\"document\"} / cpr_data_fetching_data_in_pipeline_main_pipeline_run_duration_seconds_count{scope=\"document\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pipeline stage mean duration (s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cpr_data_fetching_data_in_pipeline_main_pipeline_operation_duration_seconds_sum) by (operation)\n/ sum(cpr_data_fetching_data_in_pipeline_main_pipeline_operation_duration_seconds_count) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# validation errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\", error_type=\"validation\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow stage duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "sum by(operation) (sum_over_time(cpr_data_fetching_data_in_pipeline_main_pipeline_operation_duration_seconds_sum{environment=\"$environment\"}[$__interval]) / (sum_over_time(cpr_data_fetching_data_in_pipeline_main_pipeline_operation_duration_seconds_count{environment=\"$environment\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "filters": [
      { "id": "f3241c1c", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "data-in-pipeline" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "# network errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\", error_type=\"network\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# storage errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\", error_type=\"storage\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# transform errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\", error_type=\"transform\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# unknown errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_type, status) (max by(flow_run_name, pipeline_type, status) (max_over_time(cpr_data_fetching_data_in_pipeline_main_document_errors_total{environment=\"$environment\", error_type=\"unknown\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}