{
 "title": "Run viewer",
 "description": "View a data-in pipeline run in detail",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run name", "query": "overjoyed-marmoset" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` |= `PIPELINE_RUN_INFO`"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "count(rate({service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "# documents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` |= `PIPELINE_RUN_INFO`"
    }
   ]
  },
  {
   "title": "Total runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.prefect.flow.name=\"process-updates\" && span.prefect.run.type=\"flow\" && span.prefect.run.name=\"$run_id\"} ",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` |= `PIPELINE_RUN_INFO`"
    }
   ]
  },
  {
   "title": "Run logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 21, "x": 3, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id`"
    }
   ]
  },
  {
   "title": "Succesful stages",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(task_name) (count_over_time({service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` |= `Finished in state Completed()` [$__auto]))"
    }
   ]
  },
  {
   "title": "Error stages",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by(task_name) (count_over_time({service_name=\"data-in-pipeline\"} | flow_run_name = `$run_id` | detected_level = `error` | task_name != `` | task_name != `etl_pipeline` [$__auto]))"
    }
   ]
  }
 ]
}