services:
  app:
    container_name: geographies-api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: [fastapi, dev, app/main.py, --port, "8080", --host, 0.0.0.0]

volumes:
  navigator_postgres_data: {}
