# AWS Local Development Setup
aws-login profile="staging":
    # Login to AWS SSO with the specified profile
    @echo "🔐 Logging in to AWS SSO with profile: {{profile}}..."
    @aws sso login --profile {{profile}} || (echo "❌ AWS SSO login failed"; exit 1)
    @echo "✅ Successfully logged in to AWS SSO"

set-aws-profile profile="staging":
    # Set the AWS_PROFILE environment variable
    @export AWS_PROFILE={{profile}}
    @echo "🔄 Set AWS_PROFILE to: {{profile}}"
    @echo "💡 Remember: This only affects the current shell session"


# dev
# should be used for first run
bootstrap:
    just initial-data

initial-data environment:
    @echo "downloading latest data from s3"
    aws s3 sync s3://cpr-{{environment}}-document-cache/geographies initial-data

# This is used for fully local development with localstack
dev:
    uv sync
    docker compose --profile dev up

GITHUB_SHA := `git rev-parse HEAD`

# Deployment
deploy-override service environment tag:
    just --justfile justfile build {{service}} {{environment}} {{tag}}
    docker tag {{service}}:{{tag}} $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-west-1.amazonaws.com/{{service}}:{{tag}}
    docker tag {{service}}:{{GITHUB_SHA}} $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-west-1.amazonaws.com/{{service}}:{{GITHUB_SHA}}
    docker push $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-west-1.amazonaws.com/{{service}}:{{tag}}
    docker push $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-west-1.amazonaws.com/{{service}}:{{GITHUB_SHA}}
    aws ecs update-service \
        --cluster api-services-{{environment}} \
        --service {{service}}-{{environment}} \
        --force-new-deployment \
        --region eu-west-1
