# dev
# should be used for first run
bootstrap:
    just initial-data

    @echo "🚀 starting db docker container to load in data"
    docker compose up -d db

    @echo "⏳ waiting for Postgres to become healthy"
    @bash just-scripts/is-container-healthy.sh db

    @echo "✅ Bootstrap complete — shutting down"
    docker compose down

# TODO: we should make this environment specific when we know the locations of these files
# this isn't used for building the actual image though, so it's OK for now
initial-data:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "🔄 downloading latest dump from s3"
    LATEST_DUMP_KEY=$(aws s3api list-objects-v2 --bucket cpr-production-rds --prefix dumps/ --query 'sort_by(Contents, &LastModified)[-1].Key' --output=text)
    LATEST_DUMP_FILENAME=$(basename ${LATEST_DUMP_KEY})
    rm -r ./initial-data/*.sql
    aws s3 cp s3://cpr-production-rds/${LATEST_DUMP_KEY} ./initial-data/${LATEST_DUMP_FILENAME}


dev:
    uv sync
    docker compose --profile dev up

# build
# TODO: this needs to be tied into a lifecycle somewhere to make sure it is run if something is added
requirements:
    uv pip freeze > requirements.txt
