"""Add non-deprecated example

Revision ID: 0011
Revises: 0010
Create Date: 2023-01-20 15:47:55.867813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_v2',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['geography_v2.id'], name=op.f('fk_geography_v2__parent_id__geography_v2')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geography_v2')),
    sa.UniqueConstraint('display_value', name=op.f('uq_geography_v2__display_value'))
    )
    op.create_index(op.f('ix_geography_v2_slug'), 'geography_v2', ['slug'], unique=True)
    op.create_table('geo_statistics_v2',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('legislative_process', sa.Text(), nullable=False),
    sa.Column('federal', sa.Boolean(), nullable=False),
    sa.Column('federal_details', sa.Text(), nullable=False),
    sa.Column('political_groups', sa.Text(), nullable=False),
    sa.Column('global_emissions_percent', sa.Float(), nullable=True),
    sa.Column('climate_risk_index', sa.Float(), nullable=True),
    sa.Column('worldbank_income_group', sa.Text(), nullable=False),
    sa.Column('visibility_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geography_v2.id'], name=op.f('fk_geo_statistics_v2__geography_id__geography_v2')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_statistics_v2')),
    sa.UniqueConstraint('name', name=op.f('uq_geo_statistics_v2__name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_statistics_v2')
    op.drop_index(op.f('ix_geography_v2_slug'), table_name='geography_v2')
    op.drop_table('geography_v2')
    # ### end Alembic commands ###
