"""add_new_document_schema

Revision ID: 0011
Revises: 0010
Create Date: 2023-01-26 18:51:23.559573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_document',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('md5_sum', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('format', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physical_document'))
    )
    op.create_table('physical_document_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['physical_document.id'], name=op.f('fk_physical_document_language__document_id__physical_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_physical_document_language__language_id__language')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physical_document_language'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physical_document_language')
    op.drop_table('physical_document')
    # ### end Alembic commands ###
