"""familes and collections

Revision ID: 0013
Revises: 0012
Create Date: 2023-01-24 13:56:55.783161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_category')),
    sa.UniqueConstraint('name', name=op.f('uq_family_category__name'))
    )
    op.create_table('family_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_type')),
    sa.UniqueConstraint('name', name=op.f('uq_family_type__name'))
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant')),
    sa.UniqueConstraint('variant', name=op.f('uq_variant__variant'))
    )
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('family_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['family_category.id'], name=op.f('fk_family__category_id__family_category')),
    sa.ForeignKeyConstraint(['family_type_id'], ['family_type.id'], name=op.f('fk_family__family_type_id__family_type')),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], name=op.f('fk_family__geography_id__geography')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family'))
    )
    op.create_table('family_document',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('physical_document_id', sa.Integer(), nullable=False),
    sa.Column('cdn_url', sa.String(), nullable=True),
    sa.Column('import_id', sa.String(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('document_status', sa.Enum('CREATED', 'PUBLISHED', name='documentstatus'), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], name=op.f('fk_family_document__document_type_id__document_type')),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name=op.f('fk_family_document__family_id__family')),
    sa.ForeignKeyConstraint(['physical_document_id'], ['physical_document.id'], name=op.f('fk_family_document__physical_document_id__physical_document')),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], name=op.f('fk_family_document__variant_id__variant')),
    sa.PrimaryKeyConstraint('family_id', 'physical_document_id', name=op.f('pk_family_document'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_document')
    op.drop_table('family')
    op.drop_table('variant')
    op.drop_table('family_type')
    op.drop_table('family_category')
    # ### end Alembic commands ###
