"""add_app_user_per_org_authz

Revision ID: 0014
Revises: 0013
Create Date: 2023-05-03 20:44:16.197147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user__email'))
    )
    op.create_table('organisation_admin',
    sa.Column('appuser_email', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appuser_email'], ['app_user.email'], name=op.f('fk_organisation_admin__appuser_email__app_user')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_organisation_admin__organisation_id__organisation')),
    sa.PrimaryKeyConstraint('appuser_email', 'organisation_id', name=op.f('pk_organisation_admin'))
    )
    op.drop_index('ix_admin_email', table_name='admin')
    op.drop_table('admin_organisation')
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_organisation',
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='fk_admin_organisation__admin_id__admin'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name='fk_admin_organisation__organisation_id__organisation'),
    sa.PrimaryKeyConstraint('admin_id', 'organisation_id', name='pk_admin_organisation')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_admin')
    )
    op.create_index('ix_admin_email', 'admin', ['email'], unique=False)
    op.drop_table('organisation_admin')
    op.drop_table('app_user')
    # ### end Alembic commands ###
