"""remove deprecated db models

Revision ID: 0016
Revises: 0015
Create Date: Manually see commit

"""
from alembic import op
from alembic.op import execute
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0016'
down_revision = '0015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    execute("ALTER TYPE familycategory ADD VALUE 'UNFCCC'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading is not that simple see: https://stackoverflow.com/a/56777227
    raise NotImplementedError("We cannot remove UNFCCC category without deleting data")
    # ### end Alembic commands ###
