"""remove-family-status

Revision ID: 0017
Revises: 0016
Create Date: 2023-06-28 11:32:18.961757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0017'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family', 'family_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('family_status', postgresql.ENUM('CREATED', 'PUBLISHED', 'DELETED', name='familystatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
