"""Add data sources

Revision ID: 0019
Revises: 0018
Create Date: 2023-09-28 16:00:55.403378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_organisation_datasource__organisation_id__organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_datasource')),
    sa.UniqueConstraint('prefix', name=op.f('uq_organisation_datasource__prefix'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_datasource')
    # ### end Alembic commands ###
