"""add entity counters

Revision ID: 0019
Revises: 0018
Create Date: 2023-10-02 10:34:05.231432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_counters')),
    sa.UniqueConstraint('prefix', name=op.f('uq_entity_counters__prefix'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_counters')
    # ### end Alembic commands ###
