"""add entity counters

Revision ID: 0019
Revises: 0018
Create Date: 2023-10-02 11:32:43.825217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.CheckConstraint("prefix IN ('CCLW','UNFCCC')", name=op.f('ck_entity_counter__prefix_allowed_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_counter')),
    sa.UniqueConstraint('prefix', name=op.f('uq_entity_counter__prefix'))
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_counter')
    # ### end Alembic commands ###
