"""
Updated geography schema.

Revision ID: 0020
Revises: 0019
Create Date: 2023-11-14 16:31:12.045817

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0020"
down_revision = "0019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_constraint("ix_geography_slug", "geography", type_="unique")
    op.create_index(op.f("ix_geography_slug"), "geography", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geography_slug"), table_name="geography")
    op.create_unique_constraint("ix_geography_slug", "geography", ["slug"])
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
