"""
Added created and last modified columns for all entities

Revision ID: 0021
Revises: 0020
Create Date: 2023-11-20 15:58:31.251530

"""
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision = "0021"
down_revision = "0020"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "collection",
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "family",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "family",
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "family_event",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "family_event",
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    public_family_event_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.create_entity(public_family_event_update_last_modified)  # type: ignore

    public_collection_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.collection",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE ON public.collection
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.create_entity(public_collection_update_last_modified)  # type: ignore

    public_family_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE ON public.family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.create_entity(public_family_update_last_modified)  # type: ignore

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_family_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family",
        is_constraint=False,
        definition=""""
    BEFORE INSERT OR UPDATE ON public.family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.drop_entity(public_family_update_last_modified)  # type: ignore

    public_collection_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.collection",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE ON public.collection
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.drop_entity(public_collection_update_last_modified)  # type: ignore

    public_family_event_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_last_modified()
    """,
    )
    op.drop_entity(public_family_event_update_last_modified)  # type: ignore

    op.drop_column("family_event", "last_modified")
    op.drop_column("family_event", "created")
    op.drop_column("family", "last_modified")
    op.drop_column("family", "created")
    op.drop_column("collection", "last_modified")
    op.drop_column("collection", "created")
    # ### end Alembic commands ###
