"""
Added created column for slug table

Revision ID: 0027
Revises: 0026
Create Date: 2023-12-18 15:16:36.066595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slug",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slug", "created")
    # ### end Alembic commands ###
