"""feat!: refactor document model for consistency

Revision ID: 0002
Revises: 0001
Create Date: 2026-02-23 17:20:32.380518

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("documentdocumentlink", "documentdocumentrelationship")
    op.rename_table("documentlabellink", "documentlabelrelationship")

    op.create_table(
        "labellabelrelationship",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("label_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "related_label_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_label_id"],
            ["label.id"],
        ),
        sa.PrimaryKeyConstraint("label_id", "related_label_id"),
    )

    with op.batch_alter_table("label", schema=None) as batch_op:
        batch_op.alter_column("title", new_column_name="value")

    with op.batch_alter_table("documentdocumentrelationship", schema=None) as batch_op:
        batch_op.alter_column("source_document_id", new_column_name="document_id")
        batch_op.alter_column("relationship_type", new_column_name="type")

    with op.batch_alter_table("documentlabelrelationship", schema=None) as batch_op:
        batch_op.alter_column("relationship_type", new_column_name="type")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse column renames before table renames
    with op.batch_alter_table("documentlabelrelationship", schema=None) as batch_op:
        batch_op.alter_column("type", new_column_name="relationship_type")

    with op.batch_alter_table("documentdocumentrelationship", schema=None) as batch_op:
        batch_op.alter_column("type", new_column_name="relationship_type")
        batch_op.alter_column("document_id", new_column_name="source_document_id")

    with op.batch_alter_table("label", schema=None) as batch_op:
        batch_op.alter_column("value", new_column_name="title")

    # Drop the new table
    op.drop_table("labellabelrelationship")

    # Reverse table renames
    op.rename_table("documentlabelrelationship", "documentlabellink")
    op.rename_table("documentdocumentrelationship", "documentdocumentlink")
