"""Make item type non-nullable

Revision ID: 0005
Revises: 0004
Create Date: 2026-03-25 16:52:14.152903

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes as stypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column("type", existing_type=stypes.AutoString(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column("content_type", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
