/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FamilyPublic } from "./FamilyPublic";
import {
  FamilyPublicFromJSON,
  FamilyPublicFromJSONTyped,
  FamilyPublicToJSON,
  FamilyPublicToJSONTyped,
} from "./FamilyPublic";

/**
 *
 * @export
 * @interface APIItemResponseFamilyPublic
 */
export interface APIItemResponseFamilyPublic {
  /**
   *
   * @type {FamilyPublic}
   * @memberof APIItemResponseFamilyPublic
   */
  data: FamilyPublic;
}

/**
 * Check if a given object implements the APIItemResponseFamilyPublic interface.
 */
export function instanceOfAPIItemResponseFamilyPublic(
  value: object,
): value is APIItemResponseFamilyPublic {
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function APIItemResponseFamilyPublicFromJSON(
  json: any,
): APIItemResponseFamilyPublic {
  return APIItemResponseFamilyPublicFromJSONTyped(json, false);
}

export function APIItemResponseFamilyPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): APIItemResponseFamilyPublic {
  if (json == null) {
    return json;
  }
  return {
    data: FamilyPublicFromJSON(json["data"]),
  };
}

export function APIItemResponseFamilyPublicToJSON(
  json: any,
): APIItemResponseFamilyPublic {
  return APIItemResponseFamilyPublicToJSONTyped(json, false);
}

export function APIItemResponseFamilyPublicToJSONTyped(
  value?: APIItemResponseFamilyPublic | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: FamilyPublicToJSON(value["data"]),
  };
}
