/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GeographyDocumentCount } from "./GeographyDocumentCount";
import {
  GeographyDocumentCountFromJSON,
  GeographyDocumentCountFromJSONTyped,
  GeographyDocumentCountToJSON,
  GeographyDocumentCountToJSONTyped,
} from "./GeographyDocumentCount";

/**
 *
 * @export
 * @interface APIListResponseGeographyDocumentCount
 */
export interface APIListResponseGeographyDocumentCount {
  /**
   *
   * @type {Array<GeographyDocumentCount>}
   * @memberof APIListResponseGeographyDocumentCount
   */
  data: Array<GeographyDocumentCount>;
  /**
   *
   * @type {number}
   * @memberof APIListResponseGeographyDocumentCount
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof APIListResponseGeographyDocumentCount
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof APIListResponseGeographyDocumentCount
   */
  pageSize: number;
}

/**
 * Check if a given object implements the APIListResponseGeographyDocumentCount interface.
 */
export function instanceOfAPIListResponseGeographyDocumentCount(
  value: object,
): value is APIListResponseGeographyDocumentCount {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("page" in value) || value["page"] === undefined) return false;
  if (!("pageSize" in value) || value["pageSize"] === undefined) return false;
  return true;
}

export function APIListResponseGeographyDocumentCountFromJSON(
  json: any,
): APIListResponseGeographyDocumentCount {
  return APIListResponseGeographyDocumentCountFromJSONTyped(json, false);
}

export function APIListResponseGeographyDocumentCountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): APIListResponseGeographyDocumentCount {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(GeographyDocumentCountFromJSON),
    total: json["total"],
    page: json["page"],
    pageSize: json["page_size"],
  };
}

export function APIListResponseGeographyDocumentCountToJSON(
  json: any,
): APIListResponseGeographyDocumentCount {
  return APIListResponseGeographyDocumentCountToJSONTyped(json, false);
}

export function APIListResponseGeographyDocumentCountToJSONTyped(
  value?: APIListResponseGeographyDocumentCount | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(GeographyDocumentCountToJSON),
    total: value["total"],
    page: value["page"],
    page_size: value["pageSize"],
  };
}
