/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PhysicalDocumentPublic } from "./PhysicalDocumentPublic";
import {
  PhysicalDocumentPublicFromJSON,
  PhysicalDocumentPublicFromJSONTyped,
  PhysicalDocumentPublicToJSON,
  PhysicalDocumentPublicToJSONTyped,
} from "./PhysicalDocumentPublic";

/**
 *
 * @export
 * @interface APIListResponsePhysicalDocumentPublic
 */
export interface APIListResponsePhysicalDocumentPublic {
  /**
   *
   * @type {Array<PhysicalDocumentPublic>}
   * @memberof APIListResponsePhysicalDocumentPublic
   */
  data: Array<PhysicalDocumentPublic>;
  /**
   *
   * @type {number}
   * @memberof APIListResponsePhysicalDocumentPublic
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof APIListResponsePhysicalDocumentPublic
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof APIListResponsePhysicalDocumentPublic
   */
  pageSize: number;
}

/**
 * Check if a given object implements the APIListResponsePhysicalDocumentPublic interface.
 */
export function instanceOfAPIListResponsePhysicalDocumentPublic(
  value: object,
): value is APIListResponsePhysicalDocumentPublic {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("page" in value) || value["page"] === undefined) return false;
  if (!("pageSize" in value) || value["pageSize"] === undefined) return false;
  return true;
}

export function APIListResponsePhysicalDocumentPublicFromJSON(
  json: any,
): APIListResponsePhysicalDocumentPublic {
  return APIListResponsePhysicalDocumentPublicFromJSONTyped(json, false);
}

export function APIListResponsePhysicalDocumentPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): APIListResponsePhysicalDocumentPublic {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(PhysicalDocumentPublicFromJSON),
    total: json["total"],
    page: json["page"],
    pageSize: json["page_size"],
  };
}

export function APIListResponsePhysicalDocumentPublicToJSON(
  json: any,
): APIListResponsePhysicalDocumentPublic {
  return APIListResponsePhysicalDocumentPublicToJSONTyped(json, false);
}

export function APIListResponsePhysicalDocumentPublicToJSONTyped(
  value?: APIListResponsePhysicalDocumentPublic | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(PhysicalDocumentPublicToJSON),
    total: value["total"],
    page: value["page"],
    page_size: value["pageSize"],
  };
}
