/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Corpus
 */
export interface Corpus {
  /**
   *
   * @type {string}
   * @memberof Corpus
   */
  importId: string;
  /**
   *
   * @type {string}
   * @memberof Corpus
   */
  title: string;
  /**
   *
   * @type {number}
   * @memberof Corpus
   */
  organisationId: number;
  /**
   *
   * @type {string}
   * @memberof Corpus
   */
  corpusTypeName: string;
}

/**
 * Check if a given object implements the Corpus interface.
 */
export function instanceOfCorpus(value: object): value is Corpus {
  if (!("importId" in value) || value["importId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("organisationId" in value) || value["organisationId"] === undefined)
    return false;
  if (!("corpusTypeName" in value) || value["corpusTypeName"] === undefined)
    return false;
  return true;
}

export function CorpusFromJSON(json: any): Corpus {
  return CorpusFromJSONTyped(json, false);
}

export function CorpusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Corpus {
  if (json == null) {
    return json;
  }
  return {
    importId: json["import_id"],
    title: json["title"],
    organisationId: json["organisation_id"],
    corpusTypeName: json["corpus_type_name"],
  };
}

export function CorpusToJSON(json: any): Corpus {
  return CorpusToJSONTyped(json, false);
}

export function CorpusToJSONTyped(
  value?: Corpus | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    import_id: value["importId"],
    title: value["title"],
    organisation_id: value["organisationId"],
    corpus_type_name: value["corpusTypeName"],
  };
}
