/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GeographyDocumentCount
 */
export interface GeographyDocumentCount {
  /**
   *
   * @type {string}
   * @memberof GeographyDocumentCount
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof GeographyDocumentCount
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GeographyDocumentCount
   */
  type: string;
  /**
   *
   * @type {number}
   * @memberof GeographyDocumentCount
   */
  count: number;
}

/**
 * Check if a given object implements the GeographyDocumentCount interface.
 */
export function instanceOfGeographyDocumentCount(
  value: object,
): value is GeographyDocumentCount {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("count" in value) || value["count"] === undefined) return false;
  return true;
}

export function GeographyDocumentCountFromJSON(
  json: any,
): GeographyDocumentCount {
  return GeographyDocumentCountFromJSONTyped(json, false);
}

export function GeographyDocumentCountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GeographyDocumentCount {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    name: json["name"],
    type: json["type"],
    count: json["count"],
  };
}

export function GeographyDocumentCountToJSON(
  json: any,
): GeographyDocumentCount {
  return GeographyDocumentCountToJSONTyped(json, false);
}

export function GeographyDocumentCountToJSONTyped(
  value?: GeographyDocumentCount | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    name: value["name"],
    type: value["type"],
    count: value["count"],
  };
}
