/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FamilyDocumentPublic } from "./FamilyDocumentPublic";
import {
  FamilyDocumentPublicFromJSON,
  FamilyDocumentPublicFromJSONTyped,
  FamilyDocumentPublicToJSON,
  FamilyDocumentPublicToJSONTyped,
} from "./FamilyDocumentPublic";

/**
 *
 * @export
 * @interface PhysicalDocumentPublic
 */
export interface PhysicalDocumentPublic {
  /**
   *
   * @type {number}
   * @memberof PhysicalDocumentPublic
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PhysicalDocumentPublic
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PhysicalDocumentPublic
   */
  md5Sum: string | null;
  /**
   *
   * @type {string}
   * @memberof PhysicalDocumentPublic
   */
  sourceUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof PhysicalDocumentPublic
   */
  contentType: string | null;
  /**
   *
   * @type {string}
   * @memberof PhysicalDocumentPublic
   */
  cdnObject: string | null;
  /**
   *
   * @type {FamilyDocumentPublic}
   * @memberof PhysicalDocumentPublic
   */
  familyDocument: FamilyDocumentPublic | null;
}

/**
 * Check if a given object implements the PhysicalDocumentPublic interface.
 */
export function instanceOfPhysicalDocumentPublic(
  value: object,
): value is PhysicalDocumentPublic {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("md5Sum" in value) || value["md5Sum"] === undefined) return false;
  if (!("sourceUrl" in value) || value["sourceUrl"] === undefined) return false;
  if (!("contentType" in value) || value["contentType"] === undefined)
    return false;
  if (!("cdnObject" in value) || value["cdnObject"] === undefined) return false;
  if (!("familyDocument" in value) || value["familyDocument"] === undefined)
    return false;
  return true;
}

export function PhysicalDocumentPublicFromJSON(
  json: any,
): PhysicalDocumentPublic {
  return PhysicalDocumentPublicFromJSONTyped(json, false);
}

export function PhysicalDocumentPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PhysicalDocumentPublic {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    md5Sum: json["md5_sum"],
    sourceUrl: json["source_url"],
    contentType: json["content_type"],
    cdnObject: json["cdn_object"],
    familyDocument: FamilyDocumentPublicFromJSON(json["family_document"]),
  };
}

export function PhysicalDocumentPublicToJSON(
  json: any,
): PhysicalDocumentPublic {
  return PhysicalDocumentPublicToJSONTyped(json, false);
}

export function PhysicalDocumentPublicToJSONTyped(
  value?: PhysicalDocumentPublic | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    md5_sum: value["md5Sum"],
    source_url: value["sourceUrl"],
    content_type: value["contentType"],
    cdn_object: value["cdnObject"],
    family_document: FamilyDocumentPublicToJSON(value["familyDocument"]),
  };
}
