services:
  app:
    container_name: concepts-api-app
    build:
      context: ..
      dockerfile: concepts-api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app/concepts-api
      - ../api:/app/api
    working_dir: /app/concepts-api
    command: [fastapi, dev, app/main.py, --port, "8080", --host, 0.0.0.0]

volumes:
  navigator_postgres_data: {}
