services:
  app:
    profiles: [dev]
    container_name: concepts-api-app
    build:
      context: ..
      dockerfile: concepts-api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ..:/app
    working_dir: /app
    command:
      [
        uv,
        run,
        --project,
        concepts-api,
        fastapi,
        dev,
        concepts-api/app/main.py,
        --port,
        "8080",
        --host,
        0.0.0.0,
      ]
