# dev
# should be used for first run
bootstrap:
    just initial-data

initial-data environment:
    @echo "🔄 downloading latest data from s3"
    aws s3 sync s3://cpr-{{environment}}-document-cache/concepts initial-data
    poetry run python create_duckdb.py

dev:
    poetry install
    just initial-data production
    docker compose up

test:
    @echo "😔 no tests yet"

# You need to run this version if you have made changes to the requirements.txt file
dev-rebuild:
    just initial-data production
    docker compose up --build

prebuild environment:
    poetry install --only prebuild
    just initial-data {{environment}}

# build
# TODO: this needs to be tied into a lifecycle somewhere to make sure it is run if something is added
# sed is used here to remove a whole bunch of gumpf you can not remove with poetry v1 
requirements:
    poetry export --without-hashes --without-urls --format requirements.txt | sed 's/ ;.*//'  > requirements.txt
