FROM python:3.12-slim
WORKDIR /app
COPY app/scripts/serve_duckdb.py .
COPY .data_cache/documents.duckdb ./.data_cache/documents.duckdb
RUN pip install fastapi uvicorn duckdb
CMD ["uvicorn", "serve_duckdb:app", "--host", "0.0.0.0", "--port", "8000"]
