AWS_ACCOUNT_ID := `aws sts get-caller-identity --query 'Account' --output text`
DOCKER_REGISTRY := env_var_or_default("DOCKER_REGISTRY", AWS_ACCOUNT_ID + ".dkr.ecr.eu-west-1.amazonaws.com")

dev:
    # TODO (katy)
    echo "TODO"

test:
    uv run pytest -vv

deploy-to-prefect-local:
    uv run prefect cloud login
    just deploy-to-prefect

deploy-to-prefect:
    DOCKER_REGISTRY={{DOCKER_REGISTRY}} uv run python -m app.deploy
