config:
  aws:region: eu-west-1
  data-in-api:cdn-url: https://cdn.dev.climatepolicyradar.org

  data-in-api:api_data_reader_db_user:
    secure: AAABAEUTAQCy5azPrcernfB7Y2pwNmYTKm43qvJz5mQL/3PGsPjJG82E/lv8gPs=
