"""Dev-only entrypoint that freezes time before launching the app.

This exists so that boto3's IAM token generation produces a deterministic
output in local development, allowing us to use the resulting token as a
static password for the local Postgres container.

Not used in production — production runs `fastapi run` directly.

Script generated by Claude.
"""

import time_machine

# Freeze at a fixed instant. Must match the timestamp used when generating
# the POSTGRES_PASSWORD value for the local db container.
time_machine.travel("2026-01-01 00:00:00", tick=False).start()

# The freeze must happen before import uvicorn (and certainly before any boto3 imports)
# so it's active when those modules read time during their own initialisation.
import uvicorn  # noqa: E402

if __name__ == "__main__":
    uvicorn.run(
        "app.main:app",
        # trunk-ignore(bandit/B104)
        host="0.0.0.0",
        port=8080,
        reload=True,
        reload_dirs=["data-in-api"],
        app_dir="/app/data-in-api",
    )
