name: Daily

# See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use .env.example
        run:  cp .env.example .env

      - name: Get python Container
        run:  docker pull python:3.9

      - name: Build
        run: |
          docker-compose build
          docker images

      - name: Get dependencies  
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Start
        run: make start

      - name: Download
        run: make download_cclw_sheet

      - name: Validate  
        run:  make GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT }} validate_download

      - name: Log Dump
        if:   always()
        run:  docker-compose logs
